name: Run Selenium WebDriver Tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Select test with exact severity to run
        type: choice
        required: true
        default: fast_smoke
        options:
          - all
          - fast_smoke
          - smoke
          - full_test
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Set up environment and run tests

    steps:
    - name: Check out source repository
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install Java (required for Allure reports)
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Install Allure
      run: |
        sudo wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.tgz && 
        sudo tar -zxvf allure-2.32.0.tgz -C /opt/ && 
        sudo ln -s /opt/allure-2.32.0/bin/allure /usr/bin/allure

    - name: Run all tests
      if: "github.event.inputs.deployment_target == 'all'"
      run: |
        cd tests && pytest -v --alluredir=results
      continue-on-error: true

    - name: Run fast-smoke tests
      if: "github.event.inputs.deployment_target == 'fast_smoke'"
      run: |
        cd tests && pytest -v -m fast_smoke --alluredir=results
      continue-on-error: true

    - name: Run smoke tests
      if: "github.event.inputs.deployment_target == 'smoke'"
      run: |
        cd tests && pytest -v -m smoke --alluredir=results
      continue-on-error: true

    - name: Run full-test tests
      if: "github.event.inputs.deployment_target == 'full_test'"
      run: |
        cd tests && pytest -v -m full_test --alluredir=results
      continue-on-error: true

    - name: Generate Allure report
      run: allure generate -c cd tests/results -o _site

    - name: Save report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: _site
        path: _site
        retention-days: 3

publish-report:
    name: Publish report
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Upload pages artifacts
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4